VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
RGB_MATRIX_ENABLE = yes
OLED_ENABLE = yes
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
MOUSEKEY_ENABLE	= yes
QMK_SETTINGS = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE	= yes
CONVERT_TO = rp2040_ce
VELOCIKEY_ENABLE = yes


